src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JobApplication.cls
/**
 * Created by yurii.bubis on 10/19/2022.
 */

public with sharing class JobApplication {
   @future(callout=true)
    public static void sendCandidated(Set<Id> candidatesIds) {
       List<Candidate__c> candidates = [
               SELECT
                       Name, Age__c, Email__c, Phone__c, Position_Name__c
               FROM
                       Candidate__c
               WHERE
                       Id IN :candidatesIds
       ];
       String candidatesJson = JSON.serialize(candidates);
       System.debug('positions count ' +  candidates);

       String accessToken = RecruitmentIntegration.ReturnAccessToken();

       if (accessToken != null) {
           Http http = new Http();
           HttpRequest request = new HttpRequest();
           request.setHeader('Authorization','Bearer ' + accessToken);
           request.setHeader('Content-Type', 'application/json');
           request.setEndpoint('https://cunning-unicorn-luyqex-dev-ed.my.salesforce.com/services/apexrest/CompanyData');
           request.setMethod('POST');
           request.setBody(candidatesJson);

           HttpResponse response = http.send(request);

           System.debug(response.getBody());
       }
   }
}